export const layerConfig = [
    { key: 'hair_back', src: 'assets/hair/hair_back_base_01.png', x: 324, y: -200, visible: true, zIndex: 1 },
    { key: 'body_base', src: 'assets/body/body_torso_base_01.png', x: 524, y: 1500, visible: true, zIndex: 2 },
    { key: 'legs_left', src: 'assets/legs/leg_left_base_01.png', x: 724, y: 2200, visible: true, zIndex: 3 },
    { key: 'legs_right', src: 'assets/legs/leg_right_base_01.png', x: 924, y: 2200, visible: true, zIndex: 3 },
    { key: 'arm_left', src: 'assets/arms/arm_left_base_01.png', x: 124, y: 1200, visible: true, zIndex: 4 },
    { key: 'arm_right', src: 'assets/arms/arm_right_base_01.png', x: 1524, y: 1200, visible: true, zIndex: 4 },
    { key: 'torso_details', src: 'assets/body/body_overlay_details_01.png', x: 524, y: 1500, visible: true, zIndex: 5 },
    { key: 'neck', src: 'assets/body/body_neck_01.png', x: 924, y: 1200, visible: true, zIndex: 6 },
    { key: 'face_base', src: 'assets/head/head_base_01.png', x: 574, y: 300, visible: true, zIndex: 7 },
    { key: 'eye_left', src: 'assets/eyes/eye_left_base_01.png', x: 700, y: 850, visible: true, zIndex: 8 },
    { key: 'eye_right', src: 'assets/eyes/eye_right_base_01.png', x: 1130, y: 850, visible: true, zIndex: 8 },
    { key: 'pupil_left', src: 'assets/pupils/pupil_left_01.png', x: 735, y: 870, visible: true, zIndex: 9 },
    { key: 'pupil_right', src: 'assets/pupils/pupil_right_01.png', x: 1165, y: 870, visible: true, zIndex: 9 },
    { key: 'eyelid_upper_left', src: 'assets/eyelids/eyelid_upper_left_open_01.png', x: 700, y: 820, visible: true, zIndex: 10 },
    { key: 'eyelid_upper_right', src: 'assets/eyelids/eyelid_upper_right_open_01.png', x: 1130, y: 820, visible: true, zIndex: 10 },
    { key: 'eyelid_lower_left', src: 'assets/eyelids/eyelid_lower_left_open_01.png', x: 700, y: 880, visible: false, zIndex: 10 },
    { key: 'eyelid_lower_right', src: 'assets/eyelids/eyelid_lower_right_open_01.png', x: 1130, y: 880, visible: false, zIndex: 10 },
    { key: 'eyebrow_left', src: 'assets/eyebrows/eyebrow_left_neutral_01.png', x: 710, y: 730, visible: true, zIndex: 11 },
    { key: 'eyebrow_right', src: 'assets/eyebrows/eyebrow_right_neutral_01.png', x: 1140, y: 730, visible: true, zIndex: 11 },
    { key: 'mouth', src: 'assets/mouth/mouth_neutral_01.png', x: 884, y: 1050, visible: true, zIndex: 12 },
    { key: 'hair_front', src: 'assets/hair/hair_front_base_01.png', x: 424, y: 100, visible: true, zIndex: 13 },
    { key: 'horn_left', src: 'assets/horns/horn_left_01.png', x: 680, y: 250, visible: true, zIndex: 14 },
    { key: 'horn_right', src: 'assets/horns/horn_right_01.png', x: 1250, y: 250, visible: true, zIndex: 14 },
];

layerConfig.sort((a, b) => a.zIndex - b.zIndex);
