export const layerConfig = [
    { key: 'hair_back', src: 'assets/hair/hair_back_base_01.png', x: 424, y: -300, visible: true, zIndex: 1 },
    { key: 'body_base', src: 'assets/body/body_torso_base_01.png', x: 624, y: 1450, visible: true, zIndex: 2 },
    { key: 'legs_left', src: 'assets/legs/leg_left_base_01.png', x: 800, y: 2150, visible: true, zIndex: 3 },
    { key: 'legs_right', src: 'assets/legs/leg_right_base_01.png', x: 998, y: 2150, visible: true, zIndex: 3 },
    { key: 'arm_left', src: 'assets/arms/arm_left_base_01.png', x: 224, y: 1150, visible: true, zIndex: 4 },
    { key: 'arm_right', src: 'assets/arms/arm_right_base_01.png', x: 1574, y: 1150, visible: true, zIndex: 4 },
    { key: 'torso_details', src: 'assets/body/body_overlay_details_01.png', x: 624, y: 1450, visible: true, zIndex: 5 },
    { key: 'neck', src: 'assets/body/body_neck_01.png', x: 934, y: 1150, visible: true, zIndex: 6 },
    { key: 'face_base', src: 'assets/head/head_base_01.png', x: 624, y: 250, visible: true, zIndex: 7 },
    { key: 'eye_left', src: 'assets/eyes/eye_left_base_01.png', x: 740, y: 780, visible: true, zIndex: 8 },
    { key: 'eye_right', src: 'assets/eyes/eye_right_base_01.png', x: 1110, y: 780, visible: true, zIndex: 8 },
    { key: 'pupil_left', src: 'assets/pupils/pupil_left_01.png', x: 775, y: 795, visible: true, zIndex: 9 },
    { key: 'pupil_right', src: 'assets/pupils/pupil_right_01.png', x: 1145, y: 795, visible: true, zIndex: 9 },
    { key: 'eyelid_upper_left', src: 'assets/eyelids/eyelid_upper_left_open_01.png', x: 740, y: 745, visible: true, zIndex: 10 },
    { key: 'eyelid_upper_right', src: 'assets/eyelids/eyelid_upper_right_open_01.png', x: 1110, y: 745, visible: true, zIndex: 10 },
    { key: 'eyebrow_left', src: 'assets/eyebrows/eyebrow_left_neutral_01.png', x: 745, y: 660, visible: true, zIndex: 11 },
    { key: 'eyebrow_right', src: 'assets/eyebrows/eyebrow_right_neutral_01.png', x: 1115, y: 660, visible: true, zIndex: 11 },
    { key: 'mouth', src: 'assets/mouth/mouth_neutral_01.png', x: 949, y: 940, visible: true, zIndex: 12 },
    { key: 'hair_front', src: 'assets/hair/hair_front_base_01.png', x: 524, y: 50, visible: true, zIndex: 13 },
    { key: 'horn_left', src: 'assets/horns/horn_left_01.png', x: 720, y: 200, visible: true, zIndex: 14 },
    { key: 'horn_right', src: 'assets/horns/horn_right_01.png', x: 1230, y: 200, visible: true, zIndex: 14 },
];

layerConfig.sort((a, b) => a.zIndex - b.zIndex);
